# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Deviance
#'
#' @param data a list containing the data
#' @param state the current state of the Markov chain
#' @return a matrix containing the log case rate in time and space
#' @export
deviance <- function(data, state) {
    .Call('_epiclustR_deviance', PACKAGE = 'epiclustR', data, state)
}

#' Computed case rate per time per space
#'
#' @param data a list containing the data
#' @param state the current state of the Markov chain
#' @param smoothed set true to smooth the cases (i.e. preclude outbreaks). Defaults to false
#' @param spatial the spatial locations to compute the expected cases at.
#' @return a matrix containing the expected cases in time and space
#' @export
log_case_rate <- function(data, state, smoothed = FALSE, spatial = integer(0)) {
    .Call('_epiclustR_log_case_rate', PACKAGE = 'epiclustR', data, state, smoothed, spatial)
}

#' Computed expected cases per time per space
#'
#' @param data a list containing the data
#' @param state the current state of the Markov chain
#' @param smoothed set true to smooth the cases (i.e. preclude outbreaks). Defaults to false
#' @param spatial the spatial locations to compute the expected cases at.
#' @return a matrix containing the expected cases in time and space
#' @export
expected_cases <- function(data, state, smoothed = FALSE, spatial = integer(0)) {
    .Call('_epiclustR_expected_cases', PACKAGE = 'epiclustR', data, state, smoothed, spatial)
}

#' Compute expected cases over time
#'
#' @param data a list containing the data
#' @param state the current state of the Markov chain
#' @param smoothed set true to smooth the cases (i.e. preclude outbreaks). Defaults to false
#' @param spatial the set of spatial regions to compute the expected cases at
#' @return a matrix containing the expected cases in time over the spatial range given
#' @export
cases_per_time <- function(data, state, smoothed = FALSE, spatial = integer(0)) {
    .Call('_epiclustR_cases_per_time', PACKAGE = 'epiclustR', data, state, smoothed, spatial)
}

#' Compute expected case rate over time
#'
#' @param data a list containing the data
#' @param state the current state of the Markov chain
#' @param smoothed set true to smooth the cases (i.e. preclude outbreaks). Defaults to false
#' @param spatial the set of spatial regions to compute the expected cases at
#' @return a matrix containing the expected case rate in time over the spatial range given
#' @export
case_rate_per_time <- function(data, state, smoothed = FALSE, spatial = integer(0)) {
    .Call('_epiclustR_case_rate_per_time', PACKAGE = 'epiclustR', data, state, smoothed, spatial)
}

rbernoulli <- function(p) {
    .Call('_epiclustR_rbernoulli', PACKAGE = 'epiclustR', p)
}

rmvnorm <- function(mu, eig_sigma) {
    .Call('_epiclustR_rmvnorm', PACKAGE = 'epiclustR', mu, eig_sigma)
}

#' Update the MCMC simulation
#'
#' @param data a list containing the data
#' @param state the current state of the Markov chain
#' @param prior the priors used for the model
#' @param control the control parameters for the MCMC algorithm (e.g. tuning, blocks)
#' @return a list containing the updated state
#' @export
update <- function(data, state, prior, control) {
    .Call('_epiclustR_update', PACKAGE = 'epiclustR', data, state, prior, control)
}

