# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Deviance
#'
#' @param data a list containing the data
#' @param state the current state of the Markov chain
#' @return a matrix containing the log case rate in time and space
#' @export
deviance <- function(data, state) {
    .Call('epiclustR_deviance', PACKAGE = 'epiclustR', data, state)
}

#' Computed expected cases per time per space
#'
#' @param data a list containing the data
#' @param state the current state of the Markov chain
#' @param smoothed set true to smooth the cases (i.e. preclude outbreaks). Defaults to false
#' @return a matrix containing the expected cases in time and space
#' @export
expected_cases <- function(data, state, smoothed = FALSE) {
    .Call('epiclustR_expected_cases', PACKAGE = 'epiclustR', data, state, smoothed)
}

#' Compute expected cases over time
#'
#' @param data a list containing the data
#' @param state the current state of the Markov chain
#' @param smoothed set true to smooth the cases (i.e. preclude outbreaks). Defaults to false
#' @return a matrix containing the expected cases in time and space
#' @export
cases_per_time <- function(data, state, smoothed = FALSE) {
    .Call('epiclustR_cases_per_time', PACKAGE = 'epiclustR', data, state, smoothed)
}

rbernoulli <- function(p) {
    .Call('epiclustR_rbernoulli', PACKAGE = 'epiclustR', p)
}

rmvnorm <- function(mu, eig_sigma) {
    .Call('epiclustR_rmvnorm', PACKAGE = 'epiclustR', mu, eig_sigma)
}

#' Update the MCMC simulation
#'
#' @param data a list containing the data
#' @param i the current iteration
#' @param state the current state of the Markov chain
#' @param prior the priors used for the model
#' @param control the control parameters for the MCMC algorithm (e.g. tuning, blocks)
#' @return a list containing the updated state
#' @export
update <- function(data, i, state, prior, control) {
    .Call('epiclustR_update', PACKAGE = 'epiclustR', data, i, state, prior, control)
}

