# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rbernoulli <- function(p) {
    .Call('epiclustR_rbernoulli', PACKAGE = 'epiclustR', p)
}

rmvnorm <- function(mu, eig_sigma) {
    .Call('epiclustR_rmvnorm', PACKAGE = 'epiclustR', mu, eig_sigma)
}

#' Update the MCMC simulation
#'
#' @param data a list containing the data
#' @param i the current iteration
#' @param state the current state of the Markov chain
#' @param prior the priors used for the model
#' @param control the control parameters for the MCMC algorithm (e.g. tuning, blocks)
#' @return a list containing the updated state
#' @export
update <- function(data, i, state, prior, control) {
    .Call('epiclustR_update', PACKAGE = 'epiclustR', data, i, state, prior, control)
}

update_r <- function(cases, n, mbrg, i, state, prior, control) {
    .Call('epiclustR_update_r', PACKAGE = 'epiclustR', cases, n, mbrg, i, state, prior, control)
}

sum_u_squared <- function(U, nb) {
    .Call('epiclustR_sum_u_squared', PACKAGE = 'epiclustR', U, nb)
}

update_u <- function(cases, n, mbrg, nb, i, state, prior, control) {
    .Call('epiclustR_update_u', PACKAGE = 'epiclustR', cases, n, mbrg, nb, i, state, prior, control)
}

update_x <- function(cases, n, rgmb, state, prior, control) {
    .Call('epiclustR_update_x', PACKAGE = 'epiclustR', cases, n, rgmb, state, prior, control)
}

