// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rbernoulli
int rbernoulli(double p);
RcppExport SEXP epiclustR_rbernoulli(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    __result = Rcpp::wrap(rbernoulli(p));
    return __result;
END_RCPP
}
// rmvnorm
Rcpp::NumericVector rmvnorm(NumericVector mu, NumericMatrix eig_sigma);
RcppExport SEXP epiclustR_rmvnorm(SEXP muSEXP, SEXP eig_sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eig_sigma(eig_sigmaSEXP);
    __result = Rcpp::wrap(rmvnorm(mu, eig_sigma));
    return __result;
END_RCPP
}
// update
Rcpp::List update(List data, int i, List state, List prior, List control);
RcppExport SEXP epiclustR_update(SEXP dataSEXP, SEXP iSEXP, SEXP stateSEXP, SEXP priorSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< List >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(update(data, i, state, prior, control));
    return __result;
END_RCPP
}
// update_r
Rcpp::List update_r(NumericMatrix cases, NumericVector n, NumericVector mbrg, int i, List state, List prior, List control);
RcppExport SEXP epiclustR_update_r(SEXP casesSEXP, SEXP nSEXP, SEXP mbrgSEXP, SEXP iSEXP, SEXP stateSEXP, SEXP priorSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type cases(casesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mbrg(mbrgSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< List >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(update_r(cases, n, mbrg, i, state, prior, control));
    return __result;
END_RCPP
}
// sum_u_squared
double sum_u_squared(NumericVector U, NumericMatrix nb);
RcppExport SEXP epiclustR_sum_u_squared(SEXP USEXP, SEXP nbSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type U(USEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nb(nbSEXP);
    __result = Rcpp::wrap(sum_u_squared(U, nb));
    return __result;
END_RCPP
}
// update_u
Rcpp::List update_u(NumericMatrix cases, NumericVector n, NumericVector mbrg, NumericMatrix nb, int i, List state, List prior, List control);
RcppExport SEXP epiclustR_update_u(SEXP casesSEXP, SEXP nSEXP, SEXP mbrgSEXP, SEXP nbSEXP, SEXP iSEXP, SEXP stateSEXP, SEXP priorSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type cases(casesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mbrg(mbrgSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< List >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(update_u(cases, n, mbrg, nb, i, state, prior, control));
    return __result;
END_RCPP
}
// update_x
Rcpp::List update_x(NumericMatrix cases, NumericVector n, List rgmb, List state, List prior, List control);
RcppExport SEXP epiclustR_update_x(SEXP casesSEXP, SEXP nSEXP, SEXP rgmbSEXP, SEXP stateSEXP, SEXP priorSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type cases(casesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< List >::type rgmb(rgmbSEXP);
    Rcpp::traits::input_parameter< List >::type state(stateSEXP);
    Rcpp::traits::input_parameter< List >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(update_x(cases, n, rgmb, state, prior, control));
    return __result;
END_RCPP
}
